//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.28 at 08:44:37 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://github.com/anderson/soap-studies/schemas/countries", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.github.anderson.soapstudies.schemas.country;
